<?php
declare(strict_types=1);

/**
 * This file is part of application Jidelnicky
 * @author Milan Lysák <mlysak@email.cz>
 */

namespace App\Component\Form\Restaurant;

use App\Exception\RestaurantServiceException;
use App\Model\Manager\RestaurantManager;
use Nette\Application\UI\Form;
use Nette\ComponentModel\IComponent;

/**
 * Class RestaurantForm
 * @package App\Component\Form\Restaurant
 */
class RestaurantForm extends Form
{

    /** @var RestaurantManager */
    private $restaurantManager;

    /** @var int|null $restaurantId */
    private $restaurantId;


    /**
     * RestaurantForm constructor.
     *
     * @param int                       $restaurantId
     * @param RestaurantFormFactory     $restaurantFormFactory
     * @param RestaurantManager         $restaurantManager
     * @param RestaurantInterface       $restaurantService
     */
    public function __construct(
        int $supplierId,
        BaseFormFactory $formFactory,
        SupplierManager $supplierManager,
        SupplierInterface $supplierService
    ) {
        parent::__construct($formFactory);
        $this->supplierId = intval($supplierId);
        $this->supplierManager = $supplierManager;
        $this->supplierService = $supplierService;
    }

    /** Render add. */
    public function renderAddRestaurant()
    {

        $this->setTemplateFile('addRestaurant');
        $this->template->render();
    }


    public function createComponentAddRestaurant(): ?\Nette\Forms\Form
    {
        return parent::createComponent($name); // TODO: Change the autogenerated stub
    }


}